export const users = [
  {
    id: 1,
    nickName: "Alice96",
    name: "Alice",
    surname: "Johnson",
    email: "alice@gmail.com",
    role: "Admin",
    registrationDate: "2023-01-15",
    status: "Active",
    confirmationEmail: "Yes",
    identifier: "A12345",
    balance: 150.75,
    freeRequest: 20,
    allRequest: 20,
    totalSpend: 75.5,
  },
  {
    id: 2,
    nickName: "BobTheBuilder",
    name: "Bob",
    surname: "Smith",
    email: "bob@gmail.com",
    role: "User",
    registrationDate: "2023-02-20",
    status: "Blocked",
    confirmationEmail: "No",
    identifier: "B12345",
    balance: 150.75,
    freeRequest: 20,
    allRequest: 20,
    totalSpend: 75.5,
  },
];
